### ISSUE TITLE
Stylesheets?

### ISSUE THREAD

**Issue by guillaumegaluz** [verekia/js-stack-from-scratch#107]
I added support for stylesheets - [Here's the diff](https://github.com/guillaumeguillaume/js_app/commit/387810b52f66b6d944d7f1fc9d5a3838b75d2685)

Would you be interested in making an extra chapter for this? If so, I'd love to do a PR. Let me know!

**Comment by verekia** [comment]
Styling will get into the tutorial at some point yes, but SASS is just one option in many. In such JS stack it will probably make sense to use CSS-in-JS with Aphrodite, JSS or CSS Modules though.

**Comment by Tarabass** [comment]
https://github.com/verekia/js-stack-from-scratch/issues/72

**Comment by verekia** [comment]
Check the new release of the tutorial.
