### ISSUE TITLE
babel-register take too long 

### ISSUE THREAD

**Issue by JuanLuisClaure** [verekia/js-stack-from-scratch#109]
### Type of issue: (feature suggestion, bug, translation?)
Requiring external module babel-register take too long when write yarn start ¿why?
### Chapter:
is not a chapter is just a point I notice now I'm finish all the chapters
### If it's a bug:
if it's a bug there were something in stackoverflow but the only is [this](http://stackoverflow.com/questions/36084512/require-external-module-babel-register-takes-long-time-to-execute).

Meaby uses the old sintaxis for the gulpfile is better than use the gulpfile.babel.js. otherwhise meaby in gulp4 is no necesary uses this class of name in the file. what do you think??

**Comment by verekia** [comment]
Should not be a problem anymore.
