### ISSUE TITLE
Indonesian Translation

### ISSUE THREAD

**Issue by sqfreakz** [verekia/js-stack-from-scratch#111]
### Type of issue : Translation

I would like to translate this awesome tuts to Indonesian language 😄 

Thanks for this awesome tutorial. 
I will send a pr @verekia if the translation is ready

Collabs is welcomed 😄 

> [This](https://github.com/sqfreakz/js-stack-from-scratch) will be the repo

**Comment by ikhsanalatsary** [comment]
Hey, sounds good...  I will contribute.

**Comment by sqfreakz** [comment]
@ikhsanalatsary ok thanks bro, but i will start working in my spare time

**Comment by verekia** [comment]
@sqfreakz @ikhsanalatsary Are you guys still interested in translating the tutorial? If so, let me know in https://github.com/verekia/js-stack-from-scratch/issues/147 :)
