### ISSUE TITLE
qqhb

### ISSUE THREAD

**Issue by xhsJ88** [verekia/js-stack-from-scratch#115]
### If it's a bug:

Please try using the code provided in this repository instead of your own to see if that solves the issue. If it does, compare the content of relevant files to see if anything is missing in your version. Every chapter is automatically tested, so issues are likely coming from missing an instruction in the tutorial, a typo, or something like this. Feel free to open an issue if there is a problem with instructions though.

**Comment by kamranahmedse** [comment]
Seems like someone testing if Github has spam filter or not

**Comment by verekia** [comment]
Yep :/
