### ISSUE TITLE
Missing instructions for local http server in Ch 7?

### ISSUE THREAD

**Issue by cweekly** [verekia/js-stack-from-scratch#119]
### Type of issue: (feature suggestion, bug, translation?)
Bug / apparent gap in the instructions. 

### Chapter:
7

### Details:
Near the end of chapter 7, there's a reference made to opening the dist/index.html page in a browser:  
> Run yarn start, you should now see Webpack building your client-bundle.js file. Opening index.html in your browser should display "Wah wah, I am Browser Toby".

... but there's no mention of a recommended http server.
`webpack-dev-server` is likely to be the tool of choice (maybe in the next version of the tutorial), but meantime it might be helpful to add a one-liner, something like:

> Note to view the dist/index.html in your browser you'll want to run a local webserver; instructions for webpack-dev-server are TBD but for now you can make do with `yarn add http-server` and `http-server ./dist`

**Comment by ZeVS777** [comment]
I just opened index.html in browser and everything was fine. And in chapter 8 the same, everthing is fine.

**Comment by cweekly** [comment]
Thanks ZeVS777 - you're right, but using "file://" URLs for local dev is problematic.

**Comment by verekia** [comment]
Fixed by the new release of the tutorial :)
