### ISSUE TITLE
Korean Translation 

### ISSUE THREAD

**Issue by jiyeonseo** [verekia/js-stack-from-scratch#120]
### Type of issue: translation

Hi! 
Thank you for awesome Tutorials! 

I just start translate it to Korean!! 
Here is the 🇰🇷 repo: https://github.com/jiyeonseo/js-stack-from-scratch 

I'll submit a PR when it's ready

**Comment by verekia** [comment]
Thank you!

**Comment by verekia** [comment]
@jiyeonseo Are you still interested in translating the tutorial? If so, let me know in https://github.com/verekia/js-stack-from-scratch/issues/147 :)
