### ISSUE TITLE
Yarn is marked  as used, but won't

### ISSUE THREAD

**Issue by xstable** [verekia/js-stack-from-scratch#122]
In:  [1 - Node, NPM, Yarn, and package.json](https://github.com/verekia/js-stack-from-scratch/tree/master/tutorial/1-node-npm-yarn-package-json) you wrote: 

> Since it came out in October 2016, it received a very quick adoption and is becoming the new package manager of choice of the JavaScript community. We are going to use Yarn in this tutorial. If you want to stick to NPM you can simply replace all yarn add and yarn add --dev commands of this tutorial by npm install --save and npm install --save-dev.

But in the following Chapters only npm command is used.
Or does the yarn installation overwrite the npm-command and use yarn instead of npm?

**Comment by verekia** [comment]
Are you somehow looking at an old version of the repository? It should be Yarn everywhere.
