### ISSUE TITLE
error Command failed with exit code 1

### ISSUE THREAD

**Issue by 4reddie** [verekia/js-stack-from-scratch#128]
### Chapter: 6 ESLint

**_This is console output:_**

![error](https://cloud.githubusercontent.com/assets/4018722/22002880/3097570a-dc71-11e6-8eb8-e156fe1addcb.png)

**Comment by coffee-world** [comment]
@4reddie 
I've had the same problem, but now works well by installing again in [official doc](https://www.npmjs.com/package/eslint-config-airbnb).

I'm using Mac but it caused by just **dependencies**, so install packages again might help you to solve this.

I used
```bash
export PKG=eslint-config-airbnb
npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs yarn add --dev "$PKG@latest"
```
This command reinstalled these packages, in my case
```javascript
{
  "eslint": "^3.13.0",
  "eslint-plugin-jsx-a11y": "^3.0.2",
  "eslint-plugin-import": "^2.2.0",
  "eslint-plugin-react": "^6.9.0"
}
```

**Comment by 4reddie** [comment]
i have this dependencies:

"devDependencies": {
    "babel-preset-latest": "^6.16.0", 
    "babel-register": "^6.18.0",
    "del": "^2.2.2",
    "eslint": "^3.13.1",
    "eslint-config-airbnb": "^14.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^3.0.2",
    "eslint-plugin-react": "^6.9.0",
    "gulp": "^3.9.1",
    "gulp-babel": "^6.1.2",
    "gulp-eslint": "^3.0.1"
  }

**Comment by 4reddie** [comment]
And now I have this:


________________________________________________


C:\users\albina\Documents\webdevel\yarn_training\gulpfile.babel.js
   1:67  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
   2:1   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
   3:18  error  Casing of gulp does not match the underlying filesystem         import/no-unresolved
   3:25  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
   4:19  error  Casing of gulp-babel does not match the underlying filesystem   import/no-unresolved
   4:32  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
   5:20  error  Casing of gulp-eslint does not match the underlying filesystem  import/no-unresolved
   5:34  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
   6:17  error  Casing of del does not match the underlying filesystem          import/no-unresolved
   6:23  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
   7:38  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
   8:1   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
   9:16  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  10:27  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  11:33  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  12:17  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  13:3   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  14:1   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  15:24  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  16:13  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  17:20  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  18:20  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  19:5   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  20:20  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  21:27  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  22:35  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  22:35  error  Missing trailing comma                                          comma-dangle
  23:3   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  24:1   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  25:45  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  26:1   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  27:44  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  28:27  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  29:19  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  30:35  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  30:35  error  Missing trailing comma                                          comma-dangle
  31:3   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  32:1   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  33:45  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  34:52  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  35:25  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  36:28  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  37:6   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  38:4   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  39:1   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  40:27  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  41:40  error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  42:4   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  43:1   error  Expected linebreaks to be 'LF' but found 'CRLF'                 linebreak-style
  44:41  error  Newline required at end of file but not found                   eol-last

✖ 71 problems (71 errors, 0 warnings)

[23:40:31] 'lint' errored after 217 ms
[23:40:31] ESLintError in plugin 'gulp-eslint'
Message:
    Failed with 71 errors
______________________________________________________________

**Comment by Fakkio** [comment]
You have to set your editor to use LF as end of line (usually used on osx and linux, Win uses CRLF) or change eslint config to accept CRLF instead of LF.

**Comment by 4reddie** [comment]
How can i disable this option in gulpfile.babel.js?

**Comment by Fakkio** [comment]
you should update your package.json file:
```
{
  ...
  "eslintConfig": {
    ...
    "rules": {
      ...
      "linebreak-style": [
        "error",
        "windows"
      ],
      ...
    },
    ...
  },
  ...
}
```
In this way you'll get an error if you don't use Windows EOL.

**Comment by verekia** [comment]
Clarified in the new release of the tutorial :)
