### ISSUE TITLE
RFC: Favor npm scripts instead of gulp

### ISSUE THREAD

**Issue by amilajack** [verekia/js-stack-from-scratch#132]
Here's why I think we should migrate from gulp to npm scripts
npm scripts
 * significantly reduce js-fatigue by reducing dependencies
 * No middleware, which usually means less bugs. dont need gulp-webpack. only webpack
 * Many newer projects are reflecting this trend

Thoughts?

**Comment by Fakkio** [comment]
+1

**Comment by rubystar** [comment]
:+1:

**Comment by verekia** [comment]
I agree :) It's already happening in the v2 of this tutorial. I'll get back to it asap!

**Comment by amilajack** [comment]
I'm willing to contribute to the migration or any other areas that need help

**Comment by amilajack** [comment]
Also what are thoughts on replacing chai and mocha with jest? Jest has better react integration, is significantly faster, has better babel async/await support, and comes with assertions out of the box

**Comment by rubystar** [comment]
Personally i didn't try either of them. But one of our teams recently completely moved away from Jest to Mocha and the reason they told, `Mocha is way faster than jest`

**Comment by amilajack** [comment]
I cant confirm this. Would be great if you could show some runnable benchmarks. jest automatically parallelizes tests. Mocha relies on a 3rd party plugins for parallelism and none of them have worked for me.

**Comment by rubystar** [comment]
I recommend you to go through this https://github.com/facebook/jest/issues/116 and especially, https://github.com/facebook/jest/issues/116#issuecomment-184465423. Thanks

**Comment by amilajack** [comment]
This issue was created about a year ago, the issue is closed, and the issue has been fixed. Also besides performance as a factor, I think most users will appreciate the zero-config options. This project aims to reduce the amount of js fatigue when possible. jest is a step in the right direction, with respect to js fatigue

**Comment by rubystar** [comment]
I'll stop here and leave it to the maintainer :).

**Comment by rubystar** [comment]
BTW, I'm not stopped because i was convinced by your statement. For me, spending time on configuring the test suite(i mean only test suite, other parts may not be worth) is okay as it's one time activity. But continuing with a slow test suite is a pain as it needs to be run over and over again.
And i don't think this repo is mostly about simplifying everything but teaching how anything can be done from scratch and let the learners decide what fits them. Thanks

**Comment by verekia** [comment]
Everyone! -> https://github.com/verekia/js-stack-from-scratch/issues/133

**Comment by verekia** [comment]
Fixed by the new release of the tutorial :)
