### ISSUE TITLE
Tutorial V2: Let's do this!

### ISSUE THREAD

**Issue by verekia** [verekia/js-stack-from-scratch#133]
Hey everyone,

I finally managed to allocate some personal time to work on this major update of the tutorial.

I have created a separate repository for the final [boilerplate code of the tutorial](https://github.com/verekia/js-stack-boilerplate).

Before I start updating the instructions of the tutorial, I would appreciate some feedback regarding this boilerplate.

The major changes that happened compared to the final code of the tutorial v1 are:

- Gulp is gone, replaced by NPM scripts.
- Express has been added, with template strings for static HTML
- Support for development environment with Nodemon and production environment with PM2. Minification or sourcemaps depending on the environment via Webpack. Gzip compression enabled.
- Webpack Dev Server added, with Hot Module Replacement and react-hot-loader
- Added an asynchronous call example with redux-thunk integration.
- Linting / typechecking / testing is not launched at every file change anymore, but triggered by Git Hooks via Husky. This makes your workflow much smoother, while still protecting your repository from bad code.
- Some chapters have been combined to make it easier to maintain the tutorial.
- Replaced Chai and Mocha by Jest.
- Added React-Router, Server-Side rendering, react-helmet.
- Renamed all "dog" things and replaced it by "hello" things. It's a Hello World app after all.
- Added Twitter Bootstrap, JSS, and react-jss for styling.
- Added a Websocket example with socket.io.
- Added optional Heroku, Travis, and Coveralls integrations.

Thank you!

**Comment by austinpickett** [comment]
Looking forward to the CSS library, curious between Post-CSS and SASS.

**Comment by krisaoe** [comment]
Thanks @verekia 🍻, for this fresh take on a diluted topic!
I'm enjoying your tutoring style, and the boilerplates are both top-notch 👌

On Win 10 64 build when testing the [v2 boilerplate](https://github.com/verekia/js-stack-boilerplate):

The npm script `build` and dependent scripts `prod`, `full-check`, `precommit` and `prepush` will fail, producing

```
'NODE_ENV' is not recognized
error Command failed with exit code 1.
```

change `build` script in [`package.json`](https://github.com/verekia/js-stack-boilerplate/blob/master/package.json) to:

`"build": "rimraf dist lib && set NODE_ENV=production&& webpack -p && babel src/server -d lib/server && babel src/shared -d lib/shared",`

to fix.

**Comment by verekia** [comment]
V2 is released :)
