### ISSUE TITLE
Installing Yarn through NPM

### ISSUE THREAD

**Issue by saifalfalah** [verekia/js-stack-from-scratch#134]
**Chapter: 1**
Installing Yarn

Though it is possible to install Yarn through NPM, folks at Yarn highly recommend installing Yarn through installation method best suited for the operating system.

At: https://yarnpkg.com/en/docs/install#alternatives-tab

> Note: Installation via npm is generally not recommended. npm is non-deterministic, packages are not signed, and npm does not perform any integrity checks other than a basic SHA1 hash, which is a security risk when installing system-wide apps.
> 
> For these reasons, it is highly recommended that you install Yarn through the installation method best suited to your operating system.

I recommend changing the method of installing Yarn from using NPM to using Homebrew by default and a link to the installation page for people with other operating systems.

**Comment by verekia** [comment]
You are absolutely right. This has been updated in the V2 of the tutorial. It should be out soon. Thanks!

**Comment by SenHeng** [comment]
There is currently a problem updating Yarn installed via Homebrew if your current Node is installed via nvm or n. I suggest appending a note recommending installation via npm for those using nvm.

https://github.com/yarnpkg/yarn/issues/1505

**Comment by verekia** [comment]
Fixed by the new release of the tutorial :)

**Comment by SenHeng** [comment]
@verekia 

Do note that the official method of installing Yarn via Homebrew while also using NVM to manage node dependencies causes problems when trying to update Yarn.

I understand this is a bit of a special snowflake use case and may not affect too many people, but as an introductory course for beginners, this might become an issue in future.

https://github.com/yarnpkg/yarn/issues/1505

**Comment by krisaoe** [comment]
I agree. Due to the 'completeness' and well-deserved popularity of this tutorial, coupled with the droves of people switching to node, it wouldn't hurt to mention that there are still a few issues with yarn in certain environments.
I can find references if needed?

**Comment by SenHeng** [comment]
IMO, the better option is to remove NVM from the introductory section and move it to, for lack of a better word, the 'infra' section. Which could later also include docker and maybe CI.

**Comment by krisaoe** [comment]
I'm thinking NVM should be referred to at the beginning if at all, as it's more environment preparation related

**Comment by verekia** [comment]
I think I'll simply recommend to use the bash install, which works without relying on other package managers. NVM is still worth mentioning for people who are just beginning.

**Comment by verekia** [comment]
Fixed: https://github.com/verekia/js-stack-from-scratch/blob/master/tutorial/01-node-yarn-package-json.md#yarn

**Comment by krisaoe** [comment]
FWIW the bash install will probably only work for Windows users who are also using Linux Subsystem.
From memory, NVM is not supported on Windows. There are a couple of unofficial alternatives...
