### ISSUE TITLE
V2 Portuguese translation

### ISSUE THREAD

**Issue by bruunoromero** [verekia/js-stack-from-scratch#137]
Hey man, can I translate V2 into brazilian prortuguese?

**Comment by verekia** [comment]
Yes, but not yet! :) I'll tell you when it's ready for translation. Thank you!

**Comment by nurycaroline** [comment]
Oi @bruunoromero , i can help you into translate :D

**Comment by ygorlazaro** [comment]
So do I 😄

**Comment by verekia** [comment]
V2 is out, feel free to start translating it! :)

**Comment by verekia** [comment]
Moved to https://github.com/verekia/js-stack-from-scratch/issues/147 to reduce translation issues bloat :)
