### ISSUE TITLE
Replacing native functions should be avoided

### ISSUE THREAD

**Issue by felixsanz** [verekia/js-stack-from-scratch#14]
In the case of: **10. Immutable Redux**, I can see this:

```javascript
import { Map } from 'immutable';
import { MAKE_BARK } from '../actions/dog-actions';

const initialState = Map({
  hasBarked: false,
});
```

Isn't a bad practice to replace `Map` (which is native) with the `Map` version from Immutable?

I think it's better idea to just import Immutable and use `Immutable.Map()`.

Do you accept PR for this?

**Comment by verekia** [comment]
Good call, thanks. Can you update it in the Readme of this chapter and in the actual JS files for chapters 10, 11, 12 ?
