### ISSUE TITLE
Move `yarn add --dev pm2` instruction higher in Chapter 03

### ISSUE THREAD

**Issue by IainIsCreative** [verekia/js-stack-from-scratch#141]
### 03 - Express, Nodemon, and PM2

In chapter 3, one thing that I didn't see was an instruction `yarn add --dev pm2`. I found the tutorial confusing when the `yarn prod:start` command returned errors, and others may be confused by it as well. An explicit instruction could be helpful.

**Comment by verekia** [comment]
Well, the instruction *is* there, but it's at the end. I should probably move it to the top.

**Comment by verekia** [comment]
Fixed.
