### ISSUE TITLE
Use babel-preset-env instead of babel-preset-latest

### ISSUE THREAD

**Issue by BhaveshSGupta** [verekia/js-stack-from-scratch#142]
### If it's a bug: No
warning babel-preset-latest@6.22.0: �  preset-latest accomplishes the same task as babel-preset-env. �  Please install it with 'npm install babel-preset-env --save-dev'. '{ "presets": ["latest"] }' to '{ "presets": ["env"] }'. For more info, please check the docs: http://babeljs.io/docs/plugins/preset-env �. And let us know how you're liking Babel at @babeljs on �

**Comment by verekia** [comment]
Nice catch. I'll update the tutorial to use `babel-preset-env`. Thank you.

**Comment by verekia** [comment]
Fixed, thanks!
