### ISSUE TITLE
redux-actions@2.0.0 causes warning 'defaultNamespace' was not found in './namespaceActions'

### ISSUE THREAD

**Issue by krisaoe** [verekia/js-stack-from-scratch#143]
redux-actions@2.0.0 is the default package fetched with yarn|npm.

I received:

```
WARNING in ./~/redux-actions/es/createActions.js
29:49-65 "export 'defaultNamespace' was not found in './namespaceActions'
webpack: Compiled with warnings.
```

Possibly related to acdlite/redux-actions#197

Install @1.2.2 explicitly to fix.

**Comment by krisaoe** [comment]
If others experience the same I suggest modifying the install instructions in Chapter 5.
Thanks again 👍

**Comment by krisaoe** [comment]
[redux-actions](https://github.com/acdlite/redux-actions)@2.0.1 is published and solves this issue.

**Comment by verekia** [comment]
Well, that was easy! Thanks for the heads up though :)

**Comment by krisaoe** [comment]
I had the opportunity to contribute on another great project, so it was my absolute pleasure 🥂
