### ISSUE TITLE
V2 Russian translation

### ISSUE THREAD

**Issue by UsulPro** [verekia/js-stack-from-scratch#144]
### Translation :ru: 

Hey, We start to translate V2 to Russian!

Repo is still here: [UsulPro/js-stack-from-scratch](https://github.com/UsulPro/js-stack-from-scratch)

If anyone wants to help come [here](https://github.com/UsulPro/js-stack-from-scratch/issues/8)

**Comment by verekia** [comment]
Moved to https://github.com/verekia/js-stack-from-scratch/issues/147 :)
