### ISSUE TITLE
There is a problem with `yarn add husky --dev`

### ISSUE THREAD

**Issue by serge-nikitin** [verekia/js-stack-from-scratch#145]
There is a problem with [yarn & husky](https://github.com/typicode/husky/issues/84)

Just `yarn add husky --dev` have not installed git hooks for me. This one works for me: `yarn add husky --dev --force`

**Comment by verekia** [comment]
Interesting. It works fine for me with Yarn 0.20.3 (and even previous versions), on macOS.

What's your OS and Yarn version?

**Comment by serge-nikitin** [comment]
Sorry, it's not a bug, it's my mistake. I suppose I've installed husky before I've made 'git init'.

I tried reproduce this problem with yarn & husky, but everything works find.

**Comment by verekia** [comment]
Yay! That would make sense :) Closing then!
