### ISSUE TITLE
New chapter: Atom

### ISSUE THREAD

**Issue by verekia** [verekia/js-stack-from-scratch#148]
I'll write the Atom one, and will let the community handle other editors :)

**Comment by keplersj** [comment]
I'm very familiar with Atom if you're looking for anything in particular just ask. I've listed a few packages below I think it would be important to consider.

Packages to Consider
- `language-babel`
- `nuclide`
- `editorconfig`
- `linter`
- `linter-eslint`
- `linter-xo`
- `build`
- `build-grunt`

**Comment by verekia** [comment]
Closing this. I'm not intending to support editors anymore. There is a lot coming up in V3 already: https://github.com/verekia/js-stack-from-scratch/issues/255

I will talk about Prettier plugins for editors in the Prettier section.
