### ISSUE TITLE
New chapter: MongoDB / Mongoose

### ISSUE THREAD

**Issue by verekia** [verekia/js-stack-from-scratch#149]

**Comment by niclego** [comment]
Has this section of the tutorial been released yet?

**Comment by verekia** [comment]
Not yet. I don't think there will be any new chapter for another month or two.

**Comment by niclego** [comment]
ok! ill have to look elsewhere then.

**Comment by Flouse** [comment]
## Expecting……

**Comment by verekia** [comment]
Hey guys, sorry but that won't happen. I decided to go with PostgreSQL rather than a NoSQL DB. It will be part of the V3 of the tutorial, out next month. https://github.com/verekia/js-stack-from-scratch/issues/255
