### ISSUE TITLE
package.json in tutorial 2

### ISSUE THREAD

**Issue by BhaveshSGupta** [verekia/js-stack-from-scratch#151]
### If it's a bug:yes
 "scripts": {
   "start": "yarn dev:start",
   "dev:start": "nodemon --ignore lib --exec babel-node src/server",
-  "prod:build": "rimraf lib && babel src -d lib --ignore test.js",
+  "prod:build": "rimraf lib && babel src -d lib --ignore .test.js",
   "prod:start": "cross-env NODE_ENV=production pm2 start lib/server && pm2 logs",
   "prod:stop": "pm2 delete all",
   "test": "eslint src && flow && jest --coverage",

**Comment by verekia** [comment]
Fixed
