### ISSUE TITLE
Link issue 02 Babel to 03 - minor simple fix 

### ISSUE THREAD

**Issue by nodexchange** [verekia/js-stack-from-scratch#152]
### Type of issue: (feature suggestion, bug?)
broken link 
### Chapter:
02 - Babel, ES6, ESLint, Flow, Jest, and Husky
### Link: 
Next section: 03 - Express, Nodemon, PM2
links to: 
https://github.com/verekia/js-stack-from-scratch/blob/master/tutorial/03-express-nodemon-pm2

should link to: 
https://github.com/verekia/js-stack-from-scratch/blob/master/tutorial/03-express-nodemon-pm2.md#readme

Great tutorials guys. Really enjoy reading it.

Please try using the code provided instead of your own to see if that solves the issue. If it does, compare the content of relevant files to see if anything is missing in your version. Every chapter is automatically tested, so issues are likely coming from missing an instruction in the tutorial or a typo. Feel free to open an issue if there is a problem with instructions though.

**Comment by verekia** [comment]
Hmm... Well that's strange. I get the right link. Maybe you had an old browser tab open? I changed that recently.

**Comment by verekia** [comment]
Yeah I'm pretty sure that's what happened. All links from the current repo link to the `.md#readme`.
Closing the issue. Feel free to open it again if I'm missing something!
