### ISSUE TITLE
JSS feedback

### ISSUE THREAD

**Issue by kof** [verekia/js-stack-from-scratch#153]
https://github.com/verekia/js-stack-from-scratch/blob/master/tutorial/08-bootstrap-jss.md#readme

From JSS stand point its all correct. Its just "You cannot use some native CSS features like :hover, Media Queries, animations, or font-face." those are not the only reasons. https://github.com/cssinjs/jss/blob/master/docs/benefits.md#compared-to-inline-styles

**Comment by kof** [comment]
Performance is the biggest one.

**Comment by kof** [comment]
One more thing: u can use "composes" property for integration with bootstrap, see https://github.com/cssinjs/jss-compose

**Comment by verekia** [comment]
I added a note about other benefits with a link to your page, and an example of `composes`.

Thank you for the feedback!

https://github.com/verekia/js-stack-from-scratch/compare/551392e32af23ae533090268e3eed893a334544e...d8e897b6357f3ec359154df2bc94a1588e731332

**Comment by verekia** [comment]
Closing this issue. Feel free to re-open if you have more suggestions :)

**Comment by kof** [comment]
looks good
