### ISSUE TITLE
Custom CSS and Fonts

### ISSUE THREAD

**Issue by asgoel** [verekia/js-stack-from-scratch#154]
### If it's a bug:

Hey there, I'm having trouble getting custom CSS and fonts to work in the prod build (dev build works ok). I have custom font files in `./src/client/fonts` and a custom stylesheet in `./src/client/stylesheet/main.less`. In webpack I use `url-loader` to load my font files, but i'm getting not found errors for those specific files when I actually load the page in my browser. Ideas? Let me know if you need a more specific config.

**Comment by asgoel** [comment]
I think this is because of the `publicPath` setting in `webpack.config.babel.js`, since it's always pointing to the webpack dev server, but I could be wrong...

**Comment by asgoel** [comment]
Ended up fixing this using the `ExtractTextPlugin`. leaving this open though because technically it's still an issue

**Comment by verekia** [comment]
You are right, your issue comes from the `publicPath` always pointing to WDS.

I've tweaked the Webpack config to fix it, using a simple PNG as a test:

```js
  output: {
    filename: 'js/bundle.js',
    path: path.resolve(__dirname, 'dist'),
    publicPath: isProd ? '/static/' : `http://localhost:${WDS_PORT}/dist/`,
  },
  module: {
    rules: [
      { test: /\.png$/, use: { loader: 'file-loader', options: { name: 'img/[hash].[ext]' } } },
      { test: /\.(js|jsx)$/, use: 'babel-loader', exclude: /node_modules/ },
    ],
  },
```

In `src/client/index.js`:
```js
import image from './img/test.png'
```

The PNG is located in `src/client/img/test.png`.

This config works in both dev and prod:

In dev, the file is served by WDS at `http://localhost:7000/dist/img/hash.png`

In prod, the file is emitted to `dist/img/hash.png` and served at `http://localhost:8000/static/img/hash.png` by Express.

**Comment by verekia** [comment]
Fixed in boilerplate and in the tutorial :)

**Comment by Ramblurr** [comment]
I was working through the setup, and all was working swimmingly until I got to the JSS section. Like the disclaimer says there, CSS isn't a solved problem yet. I like that the tutorial is taking an opinionated approach with JSS.

However I think it would be great if the tutorial provided a few "basic" examples for:

1. basic static file asset serving
2. simple less/sass example

**Comment by williammanco** [comment]
@Ramblurr @verekia there are solutions to integrate css / sass? I tried it with isomorphic-webpack but it does not work
