### ISSUE TITLE
Socket.io alternatives

### ISSUE THREAD

**Issue by Sharlaan** [verekia/js-stack-from-scratch#157]
Just suggesting. How about integrating more performant alternatives like :

- [µWebSockets](https://github.com/uWebSockets/uWebSockets)
- [DeepStream](https://deepstream.io/blog/deepstream-2.0-more-than-1000-times-faster-than-socket.io/)

**Comment by verekia** [comment]
These 2 seem like great alternatives indeed. That being said, in the context of this tutorial, I don't think performance is what matters the most. Socket.io being by far the most used library for Websockets, beginners can easily find tons of resources and help online, which is more important in my opinion :)

**Comment by verekia** [comment]
I'm going to go ahead and close this thread for now. I might reopen it in the future if more people want alternatives to socket.io.
