### ISSUE TITLE
New chapter: VSCode

### ISSUE THREAD

**Issue by amilajack** [verekia/js-stack-from-scratch#159]
VScode features significantly faster performance and better out-of-the-box support for web-development. It features JS debugging, js validation, and typescript support with zero configuration. I really think we should include a section on it if we're going to add one on atom

**Comment by stevestock** [comment]
+1

**Comment by Shivamnema** [comment]
+1
Yeah definitely. I think currently it's the best tool in the market for web development. It requires few tweaks to start with However, you hack the a lot bunch of thing in it to work according to your needs.

**Comment by ButuzGOL** [comment]
+1

**Comment by verekia** [comment]
Closing this. I'm not intending to support editors anymore. There is a lot coming up in V3 already: https://github.com/verekia/js-stack-from-scratch/issues/255

I will talk about Prettier plugins for editors in the Prettier section.
