### ISSUE TITLE
yarn add husky --dev doesn't install git hooks

### ISSUE THREAD

**Issue by berkin** [verekia/js-stack-from-scratch#160]
there is an open issue about husky. https://github.com/typicode/husky/issues/84 

When using yarn, git hooks are not installed. Either execute it --force or use npm install.

**Comment by verekia** [comment]
Hmm, well it definitely does work for me on macOS with Yarn 0.20.3, but maybe in some circumstances it doesn't. I'll add a note in the tutorial for those who run into the issue, thanks.

**Comment by berkin** [comment]
probably the yarn version, i am on macOS too. Yarn version is 0.21.3

**Comment by elzii** [comment]
For those looking for solution, running `npm install --save-dev husky` will reinstall and set up the hooks.

**Comment by mauroaccornero** [comment]
Maybe it's related to https://github.com/typicode/husky/issues/84. 
I solved using yarn add --dev husky --force
I'm using ubuntu 16.4 LTS node 7.7.2 yarn 0.21.3 Husky 0.13.2

**Comment by verekia** [comment]
Note added in the tutorial :)
Thanks guys
