### ISSUE TITLE
Missing PropTypes with Flow annotations

### ISSUE THREAD

**Issue by albertbuchard** [verekia/js-stack-from-scratch#162]
Hi ! And thanks for this great intro to modern JS technology stack, I learned a great deal !

I have been looking everywhere in order to understand exactly what is happening in home.jsx. 

```jsx
// @flow

import React from 'react'
import Helmet from 'react-helmet'
import injectSheet from 'react-jss'

import ModalExample from '../modal-example'
import { APP_NAME } from '../../config'

const styles = {
  hoverMe: {
    '&:hover': {
      color: 'red',
    },
  },
  '@media (max-width: 800px)': {
    resizeMe: {
      color: 'red',
    },
  },
}

const HomePage = ({ classes }: { classes: Object }) =>
  <div>
    <Helmet
      meta={[
        { name: 'description', content: 'Hello App is an app to say hello' },
        { property: 'og:title', content: APP_NAME },
      ]}
    />
    <div className="jumbotron">
      <div className="container">
        <h1 className="display-3 mb-4">{APP_NAME}</h1>
      </div>
    </div>
    <div className="container">
      <div className="row">
        <div className="col-md-4 mb-4">
          <h3 className="mb-3">Bootstrap</h3>
          <p>
            <button type="button" role="button" data-toggle="modal" data-target=".js-modal-example" className="btn btn-primary">Open Modal</button>
          </p>
        </div>
        <div className="col-md-4 mb-4">
          <h3 className="mb-3">JSS</h3>
          <p className={classes.hoverMe}>Hover me.</p>
          <p className={classes.resizeMe}>Resize the window.</p>
        </div>
        <div className="col-md-4 mb-4">
          <h3 className="mb-3">Websockets</h3>
          <p>Open your browser console.</p>
        </div>
      </div>
    </div>
    <ModalExample />
  </div>

export default injectSheet(styles)(HomePage)
```

So far I found those articles : 

- From JSS github: https://github.com/cssinjs/react-jss
- If found this link on stateless function components definition: https://medium.com/@npverni/how-to-declare-react-components-in-2017-2a90d9f7984c#.xugp4ov0p 
- And a couple of info on react doc: https://facebook.github.io/react/docs/higher-order-components.html 

So I think I got the whole higher order component thingy. Which was not clear to me in the beginning, coming from a more classic react :) 

But there is something I still do not understand, although I have been looking around extensively. My problem is with the prop destructuring mixed with the flow declarations:

```jsx
const HomePage = ({ classes }: { classes: Object })
```

So at first I though the second "classes" does not really matter and I could have done something like

```jsx
const HomePage = ({ classes }: { albert: Object })
// and still be able to access the classes.className

// or even
const HomePage = ({ classes})
```
And it seems It does work, I do not get errors.

But in both cases I get two es-lint react error:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-prop-types.md

and a flow warning: 'Property not found in object type'

So it is written in the docs that those lint errors can be due to false positives due to component declaration.

But it got me to wonder why then your syntax does not create this error, and why did you pick it ? 
Is it a "hack" to circumvent this error, or is there some principled logic behind it I do not understand and that would help define components in this way without raising lint flags?

Thanks !

**Comment by verekia** [comment]
Thank you for pointing this out. It seems like ESLint's React plugin allows missing PropTypes when there is a Flow annotation instead.

The following gives no errors:
```js
// @flow

import React from 'react'

const Test = ({ name, age }: { name: string, age: number }) =>
  <div>
  Hello {name}, you are {age} years old.
  </div>

export default Test
```

This version gives errors:

```js
// @flow

import React from 'react'

const Test = ({ name, age }) =>
  <div>
  Hello {name}, you are {age} years old.
  </div>

export default Test

```

```
ESLint:
  error  'name' is missing in props validation  react/prop-types
  error  'age' is missing in props validation   react/prop-types
Flow:
  Destructuring Missing annotation
```

And finally this version gives a Flow warning:

```js
// @flow

import React, { PropTypes } from 'react'

const Test = ({ name, age }) =>
  <div>
  Hello {name}, you are {age} years old.
  </div>

Test.propTypes = {
  name: PropTypes.string.isRequired,
  age: PropTypes.number.isRequired,
}

export default Test
```

```
Flow: Destructuring Missing annotation
```

I should probably have put a PropType on `classes`, but I missed it because according to ESLint's React plugin, Flow annotations are enough.

From my experience, PropTypes catch a lot of things that Flow doesn't, so I'm probably going to add the PropType.

Does this help?

**Comment by verekia** [comment]
Actually, in the case of JSS' `classes` prop. We can probably omit the PropTypes. It is pretty sure that JSS will feed that object to our component, so type checking it is unnecessary in my opinion.

Either way, I hope my explanation above was clear. Going to close that thread :)

**Comment by albertbuchard** [comment]
Thanks, yes it did help but I am not sure it was a bug, I just did not understand what was really going on. I am new to react and destructuring to declare props and proptypes was a bit out of my league :)
