### ISSUE TITLE
tj/n as an alternative to nvm

### ISSUE THREAD

**Issue by stevestock** [verekia/js-stack-from-scratch#165]
### Chapter: 01

Recommend changing the nvm section to "Node Version Management Tools", and adding [tj/n](https://github.com/tj/n) as an alternative.  While nvm is by far the most popular option (17k+ stars), tj/n is still very popular (6K+ stars), and I find it much more straightforward for beginners.  Not to mention its author is the mysterious [TJ Holowaychuk](https://www.npmjs.com/~tjholowaychuk) (creator of express, stylus, commander, and many many more).

# CURRENT:

## NVM

If Node is already installed, or if you want more flexibility, install NVM ([Node Version Manager](https://github.com/creationix/nvm)), and make NVM install and use the latest version of Node for you.

# PROPOSED CHANGE:

## Node Version Management Tools

If you need the flexibility to use multiple version of Node, check out NVM ([Node Version Manager](https://github.com/creationix/nvm)) or [tj/n](https://github.com/tj/n).

**Comment by verekia** [comment]
Done :) Thank you!
