### ISSUE TITLE
Yarn test breaks because of importing immutable

### ISSUE THREAD

**Issue by berkin** [verekia/js-stack-from-scratch#168]
On chapter 5, yarn test breaks when flow is enabled and immutable is imported.
`3: import Immutable from 'immutable';
            ^^^^^^^^^ Default import from `immutable`. This module has no default export.`

There is an issue on immutable.js about it, the issue seems fixed but not on master yet.
https://github.com/facebook/immutable-js/issues/854

**Comment by verekia** [comment]
Hey, sorry about that. I literally just pushed a tweak to the instructions to install Immutable with `yarn add immutable@4.0.0-rc.2`

**Comment by verekia** [comment]
That will fix the issue until it's released in master :)

Cheers!
