### ISSUE TITLE
Babble: Create a .babelrc file at the root of your project

### ISSUE THREAD

**Issue by saliency** [verekia/js-stack-from-scratch#172]
Suggestion/Enhancement 
Chapter 2: Babel

"Create a .babelrc file at the root of your project"
Add instruction for windows users that this can be included in the package.json file.

**Comment by verekia** [comment]
That's not Windows-specific :)
Also, using `.babelrc` rather than `package.json` is by choice, to not clutter `package.json`. Cheers!

**Comment by saliency** [comment]
I'm pretty sure it is not possible in windows to create a .babelrc file.

Have you ever run your own guide off windows?

**Comment by verekia** [comment]
Yes.

https://www.quora.com/Whats-the-easiest-way-to-create-a-file-named-babelrc-on-Windows

**Comment by Yanniky** [comment]
try npm {"touch .babelrc"}

**Comment by bezdupel** [comment]
In Windows, the easiest way is to create a new file in Explorer, name it "`.babelrc.`" without quotes and answer "Yes" to the question about changing the file extension.

![1-1569420008](https://user-images.githubusercontent.com/13751556/65608074-4ec3af80-dfb6-11e9-9996-128dca0fc6bf.png)

In this way, you can create any dotfiles.

**Comment by KailashMaden** [comment]
npm touch .babelrc
