### ISSUE TITLE
dev:start not working with npm

### ISSUE THREAD

**Issue by oolong32** [verekia/js-stack-from-scratch#182]
### Refers to chapter ‘Nodemon’

Abstracting the start script (from *start* to *dev:start*) seems not to work when using npm instead of yarn. I only got the start script to work when I removed the *save-dev* line and put everything back into ‘start’:

```
"start": "nodemon --ignore lib --exec babel-node src/server",
```

**Comment by verekia** [comment]
It's because NPM needs `npm run blabla` where Yarn only needs `yarn blabla`. If you want to use NPM, add `run` everywhere.

**Comment by oolong32** [comment]
Thanks.

```
"start": "npm run start:dev",
"start:dev": "nodemon --ignore lib --exec babel-node src/server",
```

This works indeed.

*And by the way, this tutorial is exceptionally well done. Thank you again.*

**Comment by verekia** [comment]
You're very welcome :)
