### ISSUE TITLE
typo in chapter 9?

### ISSUE THREAD

**Issue by fbertone** [verekia/js-stack-from-scratch#185]
### Chapter: 9

in Heroku section, ([web setup](https://github.com/verekia/js-stack-from-scratch/blob/master/tutorial/09-travis-coveralls-heroku.md#web-setup)) you say "If that's not the done yet".
I've never heard such expression so I guess it's a typo, but maybe I'm wrong.

**Comment by verekia** [comment]
Fixed, thank you!
