### ISSUE TITLE
Missing bundle.js in Heroku 

### ISSUE THREAD

**Issue by denezra** [verekia/js-stack-from-scratch#186]
### Chapter: 09 - Travis, Coveralls, Heroku

Upon checking my work on Heroku I'm missing a file called bundle js. Looking to close to it seems we added a rule on .gitignore /dist/, so every time I upload my work its missing the bundle.js

Screenshot of Missing file:
https://www.dropbox.com/s/344ms5dewo4rx9o/Screenshot%202017-03-29%2006.24.04.png?dl=0

Link: 
https://your-project-staging-den.herokuapp.com/

**Comment by verekia** [comment]
You should not have the bundle in your Git. Heroku should build the bundle at every deployment.

Maybe you skipped the instruction about the `heroku-postbuild` task?

**Comment by denezra** [comment]
Just added that heroku-postbuild in script in package.json. But will take a look a again if I definitely miss some instruction there. 

(Sorry first time to code)

**Comment by verekia** [comment]
Awh man, this tutorial is way too advanced if that's your first time coding my friend. You should focus on the basics, and JS is probably not a great language to start with. Python would be my recommendation.

**Comment by denezra** [comment]
Oh I see but my friend recommend this to me since its easy to understand and learn.

**Comment by verekia** [comment]
Well I'm glad it is easy to understand and learn, but like the introduction says, this tutorial is made to learn how to wire some tools together. These tools are absolutely overkill if you are just beginning.

I'm going to close this issue for now :)
