### ISSUE TITLE
Flow instructions (Chapter 2) fail on Linux

### ISSUE THREAD

**Issue by ysgard** [verekia/js-stack-from-scratch#189]
...but not on OS X.  Checked and both platforms have the identical versions in package.json, but on OS X doing `yarn test` yields no errors, while on Linux (Ubuntu 16) it yields:

```
➜  proj git:(master) ✗ yarn test
yarn test v0.21.3
$ eslint src && flow 
src/dog.js:5
  5: 
     ^^^^ property `name`. Property not found in
  5: 
     ^^^^ Dog

src/dog.js:9
  9: 
     ^^^^ property `name`. Property not found in
  9: 
     ^^^^ Dog

Found 2 errors
error Command failed with exit code 2.
```

Is there additional configuration that needs to be done on Linux?

Here's the src/dog.js:
```
➜  proj git:(master) ✗ cat src/dog.js 
// @flow

class Dog {
  name: string

  constructor(name: string) {
    this.name = name
  }

  bark() {
    return `Woof woof I am ${this.name}`
  }
}

export default Dog
```

**Comment by ysgard** [comment]
Interesting, the binary itself does not report any errors:
```
➜  proj git:(master) ✗ node_modules/.bin/flow check src
Found 0 errors
```

**Comment by verekia** [comment]
That's likely coming from having a global binary of Flow that is different from the one we use in the project. Can you try to update your global version of Flow and confirm the issue is resolved?

**Comment by ysgard** [comment]
There wasn't any global version of flow installed.  This tutorial was the first time I even used node or yarn.

Weirdly, everything started to work after a reboot.  Maybe there was something wrong with the flow server?  In any case, I'm closing this now.
