### ISSUE TITLE
HMR failling because of Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by iamandrewluca** [verekia/js-stack-from-scratch#207]
### If it's a bug:
```
[WDS] App updated. Recompiling...
[WDS] App hot update...
[HMR] Checking for updates on the server...
XMLHttpRequest cannot load http://localhost:7000/dist/ffacf69653bfa6a58a17.hot-update.json.
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:8000' is therefore not allowed access.
```

### Fix:
Add to `webpack.config.babel.js`
```
devServer: {
  // ...
  headers: { 'Access-Control-Allow-Origin': '*' }
}
```

![image](https://cloud.githubusercontent.com/assets/1881266/25306820/04e911d4-279e-11e7-91be-c3cd940e59b4.png)

**Comment by samgranieri** [comment]
This worked for me

**Comment by iamandrewluca** [comment]
Maybe is related to browser environment.

**Comment by iamandrewluca** [comment]
I don't know why this happened. Now I can't reproduce this problem.

**Comment by iamandrewluca** [comment]
Sorry for reopening. I will close it for now.

**Comment by umaulana** [comment]
I encountered same issue

**Comment by Myoursky** [comment]
I encountered same issue,but with the [official code ](https://github.com/verekia/js-stack-walkthrough/tree/master/04-webpack-react-hmr),I can't reproduce this problem.

**Comment by verekia** [comment]
It is likely due to a more recent of Webpack Dev Server than the one I used in the walkthrough. I will update the tutorial asap. Sorry about that!

**Comment by zcntpz** [comment]
webpack.config.babel.js add 
`
devServer: { 
  headers: { 
    'Access-Control-Allow-Origin': 'http://localhost:8000'
  }
}
` 
to fix

**Comment by crisisdesign** [comment]
a better aproach could be import the web port from "./src/shared/config":

import { WDS_PORT, WEB_PORT } from './src/shared/config'
// [...]
devServer: { headers: { 'Access-Control-Allow-Origin': `http://localhost:${WEB_PORT}` }, },

**Comment by JiangdandanAbigale** [comment]
thanks.

**Comment by lavebug** [comment]
headers: { 'Access-Control-Allow-Origin': '*' } in webpack.config.babel.js worked. Thanks

**Comment by verekia** [comment]
It's fixed in the latest version of the tutorial.
Thanks everyone :)

**Comment by jerryOnlyZRJ** [comment]
Thank you! It works for me! 🎉
