### ISSUE TITLE
Webstorm Debugging

### ISSUE THREAD

**Issue by tulsileathers** [verekia/js-stack-from-scratch#216]
### Chapter: Any
Has anyone got any info about setting the final project setup for debugging in Webstorm? I'd like to have a real debugger on occasion. Any help would be greatly appreciated.

**Comment by NoahLE** [comment]
For debugging the React / Redux components I use React Developer Tools and Redux Developer Tools in Chrome / Firefox. For debugging the Node / Express side of things you can set up a Run/Debug Configuration by using the Node interpreter, `-r babel-register` for the Node parameters, and `src/server/index.js` for the JavaScript file. I hope this helps!

**Comment by verekia** [comment]
Hey there. I'm closing this, as I don't intend to support editors. There is a lot coming up in V3 already: https://github.com/verekia/js-stack-from-scratch/issues/255

I will talk about Prettier plugins for editors in the Prettier section.
