### ISSUE TITLE
When yarn test after flow step getting an error

### ISSUE THREAD

**Issue by lavebug** [verekia/js-stack-from-scratch#219]
### If it's a bug:

![screen shot 2017-05-17 at 1 59 38 pm](https://cloud.githubusercontent.com/assets/2514455/26173474/34666bae-3b09-11e7-8855-8c9c0abd0ec9.png)

**Comment by lavebug** [comment]
Add ignore to .flowconfig

[ignore]
.*/node_modules/eslint-plugin-jsx-a11y/src/.*

**Comment by kahirul** [comment]
Just in case someone needed
`<PROJECT_ROOT>/node_modules/eslint-plugin-jsx-a11y/src` finally works for me

**Comment by beane** [comment]
I ran into this as well, wrote a [PR that should fix it](https://github.com/verekia/js-stack-from-scratch/pull/220).
