### ISSUE TITLE
ESLint Error for Flow Type alias declaration

### ISSUE THREAD

**Issue by treepathy** [verekia/js-stack-from-scratch#226]
### Chapter: 05 - Redux, Immutable, and Fetch

**Error: 'Props' is not defined. (no-undef)**

In Button.jsx, the following code throws the above ESlint error.

```
type Props = {
  label: string,
  handleClick: Function,
}
```
flowtype plugin is configured in my .eslintrc.json.

**Comment by verekia** [comment]
Can you try to reproduce it using the code from the walkthrough, and then upgrade your flow / eslint packages to more recent versions than the walkthrough to try to identify the issue more precisely?

**Comment by treepathy** [comment]
Tried to follow through from the beginning once more. Didn't come across the issue now. Thanks!
