### ISSUE TITLE
Error setting up ESLint

### ISSUE THREAD

**Issue by GiammaCarioca** [verekia/js-stack-from-scratch#246]
When I run yarn test in chapter 02 after setting up ESLint to safely go semicolon-less in .eslintrc.json I get the following error:

Trace: 
  SyntaxError: /Users/giammacarioca/tramalabs/package.json: Unexpected string in JSON at position 116
      at JSON.parse (<anonymous>)
      at /Users/giammacarioca/.yarn/lib/cli.js:764:59
      at Generator.next (<anonymous>)
      at step (/Users/giammacarioca/.yarn/lib/cli.js:92:30)
      at /Users/giammacarioca/.yarn/lib/cli.js:103:13
      at <anonymous>

**Comment by verekia** [comment]
I'm going to assume that this isn't a problem anymore, as I clean up issues for the V3 of the tutorial. Cheers.
