### ISSUE TITLE
Add AWS Elastic Beanstalk instructions pass production build

### ISSUE THREAD

**Issue by frontendjorge** [verekia/js-stack-from-scratch#254]
### If it's a bug:

Please try to put a tutorial for upload the app in AWS Elastic Bean... its very hard make just myself

**Comment by verekia** [comment]
Hey there, sorry but I won't be supporting Beanstalk. Here are the changes that are coming up to the V3 of the tutorial: https://github.com/verekia/js-stack-from-scratch/issues/255
