### ISSUE TITLE
Chinese translation PR

### ISSUE THREAD

**Issue by pd4d10** [verekia/js-stack-from-scratch#30]
This tutorial is awesome👍. I'm translating it into Chinese:

https://github.com/pd4d10/js-stack-from-scratch

Is it possible to accept a PR, such as `README-cn.md`?

I think it will be really helpful for Chinese beginners.

**Comment by verekia** [comment]
Hi @pd4d10. Thank you very much for taking the time to translate it! The thing is, I update the content of the tutorial often, and translations will get out of sync with the English version (and its associated code) very quickly. Plus, people who download the repo to get a boilerplate project will get all the translation files as well.

For these reasons I think it would be better if translations were in their own repositories. When you are done translating it, I can put a link on the main page of the English version pointing to your fork, if that works for you :)

**Comment by pd4d10** [comment]
OK, I'll create a new repo named `js-stack-from-scratch-cn`. When I finish translation, I'll create a PR to add a link to my repo.

Good work! 👍

**Comment by verekia** [comment]
Hmm, actually, if you want to get the latest changes, it should probably stay a fork so you can pull changes easily.

**Comment by verekia** [comment]
I will write a short guide about how to translate the tutorial. Today if I have time!

Anyway, thank you very much for the translation!

**Comment by pd4d10** [comment]
Your suggestion is right. I find this:

https://help.github.com/articles/syncing-a-fork/

**Comment by toixtran** [comment]
Hi Verekia, your tutorial is really awesome. So I'm learning and translate to Vietnamese. My post of header always is "translate from your github repo link". And my blog is http://toixtran.blogspot.jp/.
Thank for sharing

**Comment by verekia** [comment]
@pd4d10 @toixtran @cicerohen Here is a guide to help you translate the tutorial! https://github.com/verekia/js-stack-from-scratch/blob/master/how-to-translate.md

**Comment by verekia** [comment]
@pd4d10 I've already added a link to your fork on the main page as an example, even if it's still work-in-progress :) Great job!

**Comment by verekia** [comment]
I will now close this issue but we can talk more about translations here if you have questions :)

**Comment by cicerohen** [comment]
@verekia thanks. :D
