### ISSUE TITLE
chapter 7: 'babel-polyfill' should be listed in the projects's dependencies

### ISSUE THREAD

**Issue by tarvos21** [verekia/js-stack-from-scratch#32]
Hi, when I am doing chapter 7, I keep getting this error from gulp:
src/client/app.js
1:1 error 'babel-polyfill' should be listed in the projects's dependencies. Run 'npm i -S babel-polyfill' to add it import/no-extraneous-dependencies

Actually in my dependencies, there is 'babel-polyfill', it's werid.
I try to add it again by 'npm i -S babel-polyfill', but it does not work, still  give me the same error.

I am on Ubuntu 16.04, and all the previous chapters work fine.

By the way, thanks for the excellent course!

**Comment by verekia** [comment]
Are you sure babel-polyfill is in your dependencies and not devDependencies ? Can you try using the code provided by the tutorial to see if you get the error too?

**Comment by johnsusek** [comment]
I had the same issue. I just needed to install babel-polyfill with yarn. I think the problem is that the wording in chapter 6 makes it sound optional. But then you get to chapter 7, and you actually need it.

**Comment by verekia** [comment]
Oh gotcha! Thanks, I'll change that.

**Comment by verekia** [comment]
Done, thanks! :)
