### ISSUE TITLE
PR: Update flow docs

### ISSUE THREAD

**Issue by amilajack** [verekia/js-stack-from-scratch#34]
Flow can now be run as an eslint plugin. Currently the docs use gulp to run flow, which is doesn't make for a good developer experience. Here's a demo:

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

Would a PR for updating the docs for this be welcome?

**Comment by medv** [comment]
That would be great

**Comment by verekia** [comment]
The thing is, this request is not really about the Flow plugin for ESLint. It's more of a request to have a chapter about setting up an editor. That's something I will consider I guess, but for now, I try to keep this tutorial IDE-agnostic. And the only way to stay generic and please everyone is via the console.

Now, about this plugin specifically, it does not add much value compared to setting up ESLint and Flow in your IDE. It just makes Flow errors use the same error messages styles as ESLint ones, really not a big deal, and not worth adding another brick of complexity in my opinion.

**Comment by verekia** [comment]
Moving this discussion to https://github.com/verekia/js-stack-from-scratch/issues/35 :)
