### ISSUE TITLE
Editor configs

### ISSUE THREAD

**Issue by amilajack** [verekia/js-stack-from-scratch#35]
I think it would be great if we could include an editor configuration describing how to setup IDE/text editors for these tools. Proper integration significantly improves developer experience.

**Comment by cpayne22** [comment]
+1
I'm coming from a Asp.Net / Visual Studio background.  I don't _need_ to use Visual Studio, and if I went for a contracting gig, I'm sure others wouldn't be using Visual Studio.

But it's not clear to me what they would be using.

It doesn't have to be war & peace, but if you're catering to a novice, it's a pretty big assumption to make that they can't install Node, but the IDE is all sorted...

**Comment by amilajack** [comment]
@verekia

> And the only way to stay generic and please everyone is via the console.

IMO, if we do that, it doesn't offer that great of a development experience when compared to running flow while typing. Just by at the amount of downloads eslint-linter gets (449,793), you can tell that there's quite a demand for linting on the fly instead of using the CLI.

>  it does not add much value compared to setting up ESLint and Flow in your IDE

I agree. I designed the plugin for large scale projects that are already using eslint and want to add flow integration easily. Flow integration doesn't have that much support across editors when compared to eslint. So its a tradeoff of having users of certain editors not have a plugin for their editor and not having full integration (autocompletion). Should we recommend both, with the eslint flow plugin as an alternative if no editor support exists for their editor?

**Comment by verekia** [comment]
I absolutely agree with linting as you type being essential.

Ohh that makes a lot of sense, you have a good point.

Okay so here is the plan:

- I'm going to write a chapter about Atom, which has a good flow support. The plugin shouldn't be needed there.

- I'll let the community write chapters about other editors, and will recommend your plugin for these other editors if the flow support is not as good as ESLint support.

Sounds good?

**Comment by amilajack** [comment]
@verekia yup! Agreed

**Comment by verekia** [comment]
Actually, let's keep that one open until the Atom chapter is out!

**Comment by verekia** [comment]
Created a more specific issue: https://github.com/verekia/js-stack-from-scratch/issues/148
