### ISSUE TITLE
gulp babel doesn't compile code

### ISSUE THREAD

**Issue by mlinko** [verekia/js-stack-from-scratch#36]
Maybe I'm doing something wrong, gulp passes and it prints out "Hello ${str}. I copied your code but it's still the same. Does anyone had the same problem

**Comment by bnealey** [comment]
Yes, I had this problem. The solution was that I had hand-typed the code, and I didn't know that the character ` is different than the character '

When I changed:
```javascript
console.log('Hello ${str}');
```
to:
```javascript
console.log(`Hello ${str}`);
```
it worked!

**Comment by verekia** [comment]
That's likely it :)

I added a comment in the Readme to clarify the backquotes thing.
