### ISSUE TITLE
no "scripts" object in initial package.json

### ISSUE THREAD

**Issue by SeanPlusPlus** [verekia/js-stack-from-scratch#37]
in the first section you instruct us to:

`In package.json, add "start": "node ." in the scripts object.`

however, after running yarn init my package.json file did not have a `scripts` object. i had to add that key manually.

**Comment by MarianoGappa** [comment]
Got stuck in the same step, but I wasn't as smart as @SeanPlusPlus so I only figured it out after reading this issue :P

This PR hopefully solves it for other people
https://github.com/verekia/js-stack-from-scratch/pull/42

**Comment by Detachment** [comment]
@SeanPlusPlus You should create this object yourself

**Comment by SeanPlusPlus** [comment]
cool, thx!
