### ISSUE TITLE
Portuguese translations!

### ISSUE THREAD

**Issue by jjaderg** [verekia/js-stack-from-scratch#38]
Hi @verekia :grinning:,

Congratulations on your project! Me and my friend [Joana](https://github.com/joanasouza), we started to [translate](https://github.com/jjaderg/js-stack-from-scratch) your project to Brazilian Portuguese. It's going to help a lot of people here who don't understand English that well.

**Comment by verekia** [comment]
You folks are lovely, thanks!

Maybe sync up with @cicerohen, who offered to work on that translation as well:

https://github.com/verekia/js-stack-from-scratch/issues/2

**Comment by verekia** [comment]
Closing this issue. Ping me with a PR when you're ready!

**Comment by verekia** [comment]
Actually I'll keep the issue open to keep track of WIPs.

**Comment by cicerohen** [comment]
@jjaderg can we work together on this? :D

**Comment by verekia** [comment]
Just added this to the translation recommendations FYI:

"Check if there is already a translation issue open for your language. If that's the case, get in touch with the folks who opened it and consider collaborating. All maintainers will be mentioned on the English repo, so team work is encouraged!"

**Comment by jjaderg** [comment]
@cicerohen sure, that's the idea.
 I already translated some things, can we sync what we already have?

**Comment by cicerohen** [comment]
@jjaderg  I not started translation yet. Please, can we swap messages to plan this translation to portuguese? 

My username on twitter is cicerohen. :)

**Comment by cicerohen** [comment]
@jjaderg we can create issues on my fork this repository to delegate responsibilities to every part of the project.

**Comment by cicerohen** [comment]
@jjaderg we can create issues on my fork this repository to delegate  responsabilities to every part of the project.

**Comment by cicerohen** [comment]
@verekia Have you created channels on tools like a Gitter?

**Comment by jjaderg** [comment]
Good idea @cicerohen

**Comment by gohackfelipe** [comment]
thats nice! I can help too!

**Comment by cicerohen** [comment]
@gohackfelipe https://github.com/verekia/js-stack-from-scratch/issues/38#issuecomment-257659434

**Comment by verekia** [comment]
Here is for you guys: https://gitter.im/js-stack-from-scratch/Translations

**Comment by verekia** [comment]
@cicerohen, @jjaderg and @joanasouza, are you interested in translating the new V2 release of the tutorial? If so, let me know in https://github.com/verekia/js-stack-from-scratch/issues/147 :)
