### ISSUE TITLE
After running yarn start in section 7, no browser window opens

### ISSUE THREAD

**Issue by SeanPlusPlus** [verekia/js-stack-from-scratch#39]
towards the end of [section 7](https://github.com/verekia/js-stack-from-scratch/tree/master/tutorial/7-client-webpack) you state:

`Run yarn start, you should now see Webpack building your client-bundle.js file, and opening index.html in your browser should display "Wah wah, I am Browser Toby".`

the webpack build is okay, but my browser does not open a new window. is there something special i need to do?

**Comment by ug02fast** [comment]
I'm trying to understand this same issue. Is yarn supposed to be hosting the app on a particular port?

**Comment by metaloha** [comment]
I think it just means that you should open `index.html` in your browser, not that yarn will actually open the browser for you.

**Comment by rocketNeck** [comment]
Two sentences might remove the confusion. 

Run yarn start, you should now see Webpack building your client-bundle.js file. Opening index.html in your browser should display "Wah wah, I am Browser Toby".

**Comment by verekia** [comment]
I agree, that was confusing :)

Fixed: https://github.com/verekia/js-stack-from-scratch/commit/08f2fa6046718976dc231b6d001a0e6d16fecaad

Thanks @rocketNeck

**Comment by SeanPlusPlus** [comment]
totally works! thx!

**Comment by josesuarezcordova** [comment]
Sorry , I get the same error after run 

yarn start

seems like everything fine

[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.37:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.37:3001

the browser open but never load the web, my project is under bedrock the structure of web folder is

web
----app
------mu-plugins
------plugins
------themes
------uploads
----wp
-------wp-admin
-------wp-content
-------wp-includes

thanks!
