### ISSUE TITLE
sourcemap / frontend debugging support

### ISSUE THREAD

**Issue by iivvoo** [verekia/js-stack-from-scratch#43]
Does this setup give a workable frontend debugging experience? With source maps providing the mapping between modules and es6 code in stead of minified concatenated app.js files containing tens thousands lines of transpiled-to-ES5 code totally not resembling the original ES6 source?

I'm asking because this seems to be a really hard problem for the EmberJS team to solve and noone strangely seems to care enough

**Comment by verekia** [comment]
Yes, source maps are generated by Webpack.

https://github.com/verekia/js-stack-from-scratch/blob/master/tutorial/7-client-webpack/README.md#webpack
