### ISSUE TITLE
Discussion about yarn

### ISSUE THREAD

**Issue by torifat** [verekia/js-stack-from-scratch#47]
> Yarn is another package manager which is much faster than NPM, caches packages offline, and fetches dependencies more predictably.
1. `npm` caches packages offline too. Or, did you mean the offline install option in yarn?
2. I didn't understand what do you mean by "fetches dependencies more predictably"

**Comment by verekia** [comment]
1. Yes, I mean the offline installation of packages with Yarn.
2. `yarn.lock` ensures that every collaborator is running the same version of packages (similarly to npm's shrinkwrap - but auto-generated by default which helps enforcing it)

https://code.facebook.com/posts/1840075619545360

Would you recommend a different wording?

**Comment by torifat** [comment]
Yarn is another package manager which is much faster than NPM, has offline support, and fetches dependencies more predictably.

**Comment by torifat** [comment]
And, maybe link this: https://yarnpkg.com/en/docs/yarn-lock

BTW, 👍 for the awesome work 😄

**Comment by MoOx** [comment]
Yarn is "just" a npm registry client.

**Comment by verekia** [comment]
Done :)
