### ISSUE TITLE
Reducing the perceived fatigue

### ISSUE THREAD

**Issue by silvenon** [verekia/js-stack-from-scratch#48]
Many people point to this tutorial as an illustration of JS fatigue, I disagree with them and have a couple of suggestions:

- mention create-react-app somewhere at the beginning
- drop "ES6" when listing tools at the intro ("ES6, Babel, Gulp,…") because Babel already does ES6
- consider adding Jest to the list, which is an alternative to the Mocha/Chai/Sinon combo, but it's a single tool so it looks less intimidating
- clarify in the intro that many of these tools are optional, people don't have to lint, type-check, have a single app state, enforce immutability etc.
- clarify in the intro that some of the mentioned tools can be alternatives to each other (yarn/npm, gulp/webpack…)

Apply whichever suggestions you want or close this issue, I just wanted to share that feedback. 😉

**Comment by verekia** [comment]
That's really a great suggestion, thanks man :) I'll rework that intro to make it less overwhelming.

**Comment by verekia** [comment]
I removed the intimidating list of tools, mentioned that this is only for web apps, not simple stuff, and added a part about create-react-app. Thanks!

**Comment by silvenon** [comment]
Looks great now!
