### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by atakangktepe** [verekia/js-stack-from-scratch#53]
### Type of issue: Translation

I'm translating this repo to Turkish language, I'll ping you with a PR when I'm ready @verekia !
Thanks for this awesome tutorial!

You can Follow/Contribute from here: https://github.com/atakangktepe/js-stack-from-scratch

**Comment by verekia** [comment]
Sounds good, thanks!

**Comment by verekia** [comment]
Here is the Gitter if you wanna join: https://gitter.im/js-stack-from-scratch/Translations

**Comment by verekia** [comment]
@atakangktepe Are you interested in translating the new version of the tutorial? If so, let me know in https://github.com/verekia/js-stack-from-scratch/issues/147 ! Thank you :)
