### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by AlexR1712** [verekia/js-stack-from-scratch#55]
### Type of issue: Translation

I'm translating this repo to Spanish language, I'll send to you @verekia a PR when translation is ready!
This tutorial is amazing!
Thanks! 

> Here is the repo for Spanish Version: https://github.com/AlexR1712/js-stack-from-scratch

**Comment by verekia** [comment]
Sweet, thanks!

**Comment by asdrubalivan** [comment]
Hi @AlexR1712, I would like to contribute. Ping me if you're interested

**Comment by AlexR1712** [comment]
@asdrubalivan Perfect, I communicate with you shortly. :+1:

**Comment by verekia** [comment]
Here is the Gitter for you guys: https://gitter.im/js-stack-from-scratch/Translations

**Comment by JMEspiz** [comment]
@AlexR1712 @asdrubalivan. Hi Guys, I want to contribuite with the translation.

**Comment by Alcondez** [comment]
@AlexR1712 @asdrubalivan @JMEspiz Hi Guys, I would like to contribute as well, let me know if you agree.

**Comment by verekia** [comment]
@AlexR1712 @JMEspiz @Alcondez @asdrubalivan Are you guys interested in translating the V2 of the tutorial? If so, let me know in https://github.com/verekia/js-stack-from-scratch/issues/147 ! Thanks :)
