### ISSUE TITLE
Naming convention conflicts Airbnb

### ISSUE THREAD

**Issue by opportunato** [verekia/js-stack-from-scratch#56]
Airbnb styleguide is used for this project, but naming of files (button.jsx, bark-message.jsx, etc.) conflicts with the airbnb one:

> A base filename should exactly match the name of its default export.
https://github.com/airbnb/javascript#naming--filename-matches-export

If you agree, I can open a pull request with renamed files.

**Comment by verekia** [comment]
Should be fixed by the new release of the tutorial :)
