### ISSUE TITLE
Chapter 2 - Dfiference between "dependencies" and "devDependencies" - Confusing

### ISSUE THREAD

**Issue by begincalendar** [verekia/js-stack-from-scratch#64]
### Type of issue: 
bug

### Chapter: 
2 - Installing and using a package

### Description

The end note about the difference between dependencies and dev-dependencies is quite confusing to me, in that it leaves me confused, rather than enlightened about the difference between the two.

This is the specific sentence that I'm referring to:

> "dependencies" is more general than "devDependencies", which are packages that you only need during development, not production (typically, build-related packages, linters, etc)

Could it possibly be re-worded and/or broken into multiple sentences?

**Comment by austinpickett** [comment]
It does seem a little weird that `yarn start` requires gulp to start and sometimes I get a little confused as to the two myself, but let me see if I can make light of it:

**Dependencies**: libraries you _need_ for your application to function: (jQuery, React, Redux, lodash, etc)
**Dev Dependencies**: anything the developer sees to make their lives easier during development: (webpack, gulp, grunt, less, sass, linters, and testing frameworks).

**Comment by begincalendar** [comment]
Something like that sounds much better to me.

**Comment by austinpickett** [comment]
I'm not sure this is really considered a bug. I do understand that @begincalendar is struggling with the concept of dependencies and devDependencies but with the level of familiarity required to use this repo, one should have a fair understanding of the two without an in depth definition.

I think the author explained it well without going into detail on how npm/yarn work

**Comment by begincalendar** [comment]
It's not a matter of your experience coming into this guide, it's a matter of grammar and wording.

Do you disagree that:

> "dependencies" is more general than "devDependencies", which are packages that you only need during development, not production (typically, build-related packages, linters, etc)

...is more ambiguous than:

> Dependencies: libraries you need for your application to function: (jQuery, React, Redux, lodash, etc)
Dev Dependencies: anything the developer sees to make their lives easier during development: (webpack, gulp, grunt, less, sass, linters, and testing frameworks).

?

It doesn't have to be called a bug, call it what you want, but why go for something ambiguous to at least one person?

P.S. I don't appreciate you assuming I'm struggling with the concepts. The ambiguity of the sentence required me to research it and get clarification elsewhere, as opposed to just gaining an immediate understanding.

**Comment by verekia** [comment]
Thanks guys, that's a better way to explain it. I'll update the readme :)
