### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by RadLikeWhoa** [verekia/js-stack-from-scratch#67]
### Type of issue: Translation

I'm translating this repo to German, I'll submit a PR once I'm done translating.

You can Follow/Contribute from here: https://github.com/RadLikeWhoa/js-stack-from-scratch

**Comment by verekia** [comment]
Thank you!

**Comment by verekia** [comment]
@RadLikeWhoa Are you interested in translating the V2 of the tutorial? If so, let me know in https://github.com/verekia/js-stack-from-scratch/issues/147 ! Thanks :)
