### ISSUE TITLE
Tutorial 4 needs a gulp install step.

### ISSUE THREAD

**Issue by folktrash** [verekia/js-stack-from-scratch#70]
### Tutorial 4
* proceed to yarn start
* observe gulp is not a command
### New
* run yarn add --dev gulp
* retry yarn start
* observe Wah Wah

**Comment by verekia** [comment]
The Gulp setup is done in chapter 3, so it should already be installed when you reach chapter 4. It's in `package.json` so maybe you just needed to run `yarn` to install all the dependencies.

**Comment by folktrash** [comment]
I see. (same for #5). I'm walking through everything right now, and going "step by step"' feels like there's a step missing in 4 & 5. Thanks so much for making this!

**Comment by verekia** [comment]
Should be fixed by the new release of the tutorial :)
