### ISSUE TITLE
What are the plans for styling?

### ISSUE THREAD

**Issue by Tarabass** [verekia/js-stack-from-scratch#72]
I see that there are plans to implement some styling. Which modules are you planning to use? For now I use a combination of webpack loaders to load sass/css. But maybe there are better packages:

[css-loader](https://github.com/webpack/css-loader)
[postcss-loader](https://github.com/postcss/postcss-loader)
[sass-loader](https://github.com/jtangelder/sass-loader)

**Comment by verekia** [comment]
That's a tricky one, there are many options here so I'm not sure yet. One important factor is that server-side rendering should be styled. I'm mostly considering CSS Modules, JSS, or Aphrodite.

**Comment by Tarabass** [comment]
css-loader is the css-modules loader for [webpack](https://github.com/css-modules/webpack-demo), isn't it? Never used [JSS](https://github.com/cssinjs/jss), I don't render on the server, but looks promising :)

**Comment by Ernier967** [comment]
Minutes prior to see the fight

**Comment by verekia** [comment]
See the new release of the tutorial, chapter 08.

Related: https://github.com/verekia/js-stack-from-scratch/issues/139
