### ISSUE TITLE
Don't we need webpack dev server?

### ISSUE THREAD

**Issue by Tarabass** [verekia/js-stack-from-scratch#73]
Don't we need [webpack dev server](https://github.com/webpack/webpack-dev-server)?

**Comment by verekia** [comment]
Yes, that's one of the many things I have to add to the tutorial :)
I'm working on some major changes which need to go out first, and then I'll add webpack dev server.

**Comment by mudits1990** [comment]
When can we expect webpack dev server[https://github.com/webpack/webpack-dev-server](url) to be introduced in the tutorial?

**Comment by verekia** [comment]
Soon after the release of the v2 of the tutorial, which should happen in 2-3 weeks. If not, January.

**Comment by verekia** [comment]
Fixed by the new release of the tutorial :)
