### ISSUE TITLE
introduction to bower as frontend package manager

### ISSUE THREAD

**Issue by dongyb80** [verekia/js-stack-from-scratch#78]
### Type of issue: (feature suggestion, bug, translation?)
feature suggestion
### Suggestion
I see many projects use bower as package manager for frontend. May you add introduction to bower?

**Comment by verekia** [comment]
Bower is actually used less and less, in favor of NPM/Yarn packages. Most front-end libraries are on the NPM registry.

**Comment by dongyb80** [comment]
Thanks for the information! Actually I am glad to hear that.

**Comment by verekia** [comment]
You're welcome!
