### ISSUE TITLE
Lint error with airbnb & react-a11y plugin

### ISSUE THREAD

**Issue by domino14** [verekia/js-stack-from-scratch#81]
### If it's a bug:

Trying to lint results in the following error output:

```
Error: /mydir/node_modules/eslint-config-airbnb/rules/react-a11y.js:

	Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
	Value "" is the wrong type.

```

**Comment by NicolaFerracin** [comment]
For anyone who stumbled upon this problem, I found a quick fix:
- remove all packages installed in chapter 6 running `yarn remove eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y eslint`
- reinstall them all using the specific version taken from chapter 6 package.json, with `yarn add --dev eslint@3.8.1 eslint-config-airbnb@12.0.0 eslint-plugin-import@2.0.1 eslint-plugin-jsx-a11y@2.2.3 eslint-plugin-react@6.4.1`

This fixed the problem for me, hope it works for you too @domino14  :)

**Comment by domino14** [comment]
Yep it did. Thanks!

**Comment by ralphwillgoss** [comment]
This error could morph over time as the packages change, @NicolaFerracin have you done a PR for this?

**Comment by isafrus5** [comment]
Thansk @NicolaFerracin it works!!

**Comment by ralphwillgoss** [comment]
Thanks @NicolaFerracin

**Comment by verekia** [comment]
Hey everyone,

Sorry about that, it's the kind of stuff that can break randomly as dependencies evolve :)

There is a better way to install Airbnb's ESLint configuration than what I've described in the tutorial.

Refer to the [official doc](https://www.npmjs.com/package/eslint-config-airbnb). for now. I updated the instructions in the v2 of the tutorial which is still WIP. Basically you should run:

```bash
export PKG=eslint-config-airbnb
npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs yarn add --dev "$PKG@latest"
```
