### ISSUE TITLE
Can't Run Gulp with gulpfile.babel.js

### ISSUE THREAD

**Issue by rmurcek** [verekia/js-stack-from-scratch#84]
### Chapter: 5

I can run gulp in prior chapters, but not after converting to gulpfile.babel.js

5-es6-modules-syntax> gulp
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at Liftoff.buildEnvironment (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:113:52)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:181:32)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:174:9)
    at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:148:9
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:79:12
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:35:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

```
node -v
v6.9.1
npm -v
2.15.9
```

**Comment by austinpickett** [comment]
Can you print your gulpfile?

**Comment by rmurcek** [comment]
Here you go @austinpickett 

gulpfile.babel.js
```
import gulp from 'gulp';
import babel from 'gulp-babel';
import del from 'del';
import { exec } from 'child_process';

const paths = {
  allSrcJs: 'src/**/*.js',
  libDir: 'lib',
};

gulp.task('clean', () => {
  return del(paths.libDir);
});

gulp.task('build', ['clean'], () => {
  return gulp.src(paths.allSrcJs)
    .pipe(babel())
    .pipe(gulp.dest(paths.libDir));
});

gulp.task('main', ['build'], (callback) => {
  exec(`node ${paths.libDir}`, (error, stdout) => {
    console.log(stdout);
    return callback(error);
  });
});

gulp.task('watch', () => {
  gulp.watch(paths.allSrcJs, ['main']);
});

gulp.task('default', ['watch', 'main']);
```

**Comment by rmurcek** [comment]
Interestingly, this failure also occurs in the chapter 6 and 7 directories, but not in chapter 8. Again, this is from origin/master 576dd2b . Thanks!

**Comment by verekia** [comment]
Gulp is gone in the new release of the tutorial.
