### ISSUE TITLE
Deploying to production?

### ISSUE THREAD

**Issue by maxcountryman** [verekia/js-stack-from-scratch#85]
First off I'd like to thank you for this fantastic resource. It's absolutely indispensable to the community! 

Second I'm wondering if the plans for tutorial sections covering production mode have been put on hold? I see you have a branch for setting up Express and updating Gulp to accommodate--but it looks like some essential bits are missing, e.g. minification. I also noticed the version 2 branch doesn't include a section for this.

It would be fantastic to at least see the production branch somehow incorporated into the second version of the tutorial--that sort of closes the loop as it were.

**Comment by verekia** [comment]
It is absolutely happening in the v2 of the tutorial. The branch is still a big WIP and a lot will change. The Express chapter will cover dev/prod and minification will be in the Webpack chapter :)

**Comment by austinpickett** [comment]
@varekia are you using express server instead of webpack-dev-server?

**Comment by verekia** [comment]
I'm not going to add webpack-dev-server yet. I need to get the v2 out first (with Express), and will bring webpack-dev-server into the mix later :)

**Comment by verekia** [comment]
Fixed by the new release of the tutorial :)
