### ISSUE TITLE
documentation generation

### ISSUE THREAD

**Issue by fbertone** [verekia/js-stack-from-scratch#86]
### Chapter: new chapter

What about a chapter on automatic documentation generation?
Like https://github.com/reactjs/react-docgen
I think it could be useful

**Comment by verekia** [comment]
Hmm... I would tend to favor internal documentation (comments, good naming, Flow annotations, structure imposed by libraries like Redux), rather than generating an external doc. Closing this for now but I may open it again if there is demand for it.
