### ISSUE TITLE
Georgian Translation

### ISSUE THREAD

**Issue by brunjick** [verekia/js-stack-from-scratch#87]
### Type of issue: Translation

Just started translating into Georgian, hope to get done in a week or so 😊😊😊
Thanks for amazing work 👍

https://github.com/brunjick/js-stack-from-scratch

**Comment by verekia** [comment]
Thank you very much! Just a little heads up though, the version 2 of the tutorial should come out in the next weeks, so there will be lots of changes. It's up to you if you want to translate the v1 or wait :)

**Comment by brunjick** [comment]
Hi @verekia , is 2.0 branch ready to start translating?

**Comment by verekia** [comment]
Yeahhhh.... sadly, no. I was a little too optimistic when I said in the next weeks. I think a month from now would be a safer bet.

**Comment by verekia** [comment]
V2 is out, feel free to start translating it! :)

**Comment by verekia** [comment]
@brunjick Moving this thread to https://github.com/verekia/js-stack-from-scratch/issues/147. Let me know if you are still interested!

**Comment by brunjick** [comment]
@verekia Yes, will be starting work on it from next week 🙏

**Comment by verekia** [comment]
Awesome!
