### ISSUE TITLE
Eslint complains about comma-dangle

### ISSUE THREAD

**Issue by dylnclrk** [verekia/js-stack-from-scratch#90]
### Type of issue: (feature suggestion, bug, translation?)
bug

### Chapter:
6 (eslint)

### Issue:
Newer versions of airbnb's eslint configuration complain about a lack of dangling commas on multi-line function invocations. For example:

```javascript
gulp.task('build', ['lint', 'clean'], () =>
   gulp.src(paths.allSrcJs)
     .pipe(babel())
     .pipe(gulp.dest(paths.libDir))
);
```
Causes linter error: `error  Missing trailing comma  comma-dangle`.

**Note:** This wouldn't be a problem if people copied `package.json` from the tutorial. But since people generate their own `package.json`, they will have the most recent version of airbnb's eslint configuration. I don't think people should be instructed to copy `package.json`, it's important to learn how to generate it with `yarn`.

### How to reproduce: 
1. Update `eslint-config-airbnb`:
   1. in `package.json` change: `"eslint-config-airbnb": "^12.0.0",` to `"eslint-config-airbnb": "^13.0.0",`
   1. run `yarn install`
1. run `yarn start`
1. See something to the effect of: 
```
$ yarn start
yarn start v0.16.1
$ gulp 
[15:58:51] Requiring external module babel-register
[15:58:52] Using gulpfile ~/js-stack-from-scratch/tutorial/6-eslint/gulpfile.babel.js
[15:58:52] Starting 'watch'...
[15:58:52] Finished 'watch' after 20 ms
[15:58:52] Starting 'lint'...
[15:58:52] Starting 'clean'...
[15:58:52] Finished 'clean' after 26 ms
[15:58:53] 
/Users/some-user/js-stack-from-scratch/tutorial/6-eslint/gulpfile.babel.js
  22:35  error  Missing trailing comma  comma-dangle
  30:35  error  Missing trailing comma  comma-dangle

✖ 2 problems (2 errors, 0 warnings)
```

### Possible fixes:

Wrap it in parens:
```javascript
gulp.task('build', ['lint', 'clean'], () => (
   gulp.src(paths.allSrcJs)
     .pipe(babel())
     .pipe(gulp.dest(paths.libDir))
));
```
or add a trailing comma:
```javascript
gulp.task('build', ['lint', 'clean'], () =>
   gulp.src(paths.allSrcJs)
     .pipe(babel())
     .pipe(gulp.dest(paths.libDir)),
);
```

### PR

I whipped something up here: #91 
If it looks good, I can make similar PRs for the other chapters (if necessary).

### Other relevant discussion

eslint/eslint#7588

**Comment by dylnclrk** [comment]
Here's my PR: https://github.com/verekia/js-stack-from-scratch/pull/91

**Comment by dylnclrk** [comment]
And somewhat relevant discussion on the eslint/eslint repository:
https://github.com/eslint/eslint/issues/7588

**Comment by domino14** [comment]
The trailing comma just looks totally wrong there. That has to be a bug.

**Comment by amandogra** [comment]
I solved it by adding a rule in package.json under eslintConfig > rules : 
```
      "comma-dangle": [
        "error",
        "never"
      ]
```
Now it doesn't check for missing trailing commas instead asks to remove it.

**Comment by domino14** [comment]
That doesn't quite fix the issue. The trailing comma rule is a good rule, it's just implemented wrong in this case.

**Comment by dylnclrk** [comment]
@domino14 agreed that trailing commas are good style, e.g. 

```
someFunction(
  arg1,
  arg2,
  [arg3a, arg3b],
);
```

When you say,
> The trailing comma rule is a good rule, it's just implemented wrong in this case.

do you mean that the rule should not flag,
```javascript
gulp.task('build', ['lint', 'clean'], () =>
   gulp.src(paths.allSrcJs)
     .pipe(babel())
     .pipe(gulp.dest(paths.libDir)),
);
```

as a violation of the trailing comma rule? (e.g. it should collapse multi-line arrow functions or something similar) Do we think that ESLint/Airbnb will address this issue soon?  If not, it may be nice to adjust the code examples to avoid this error in the tutorial.

Also, it's been two weeks so perhaps this isn't a problem anymore.

**Comment by verekia** [comment]
Hey, sorry everyone, it's pretty difficult for me to look into these issues these days, as I'm backpacking in Asia and barely get any moment to open a laptop. I will get back to you as soon as I can.

**Comment by kevinrambaud** [comment]
Same here, had to add comma-dangle in disallowed rules

```javascript
/* eslint-disable import/no-extraneous-dependencies, comma-dangle, no-console */
import gulp from 'gulp';
import babel from 'gulp-babel';
import del from 'del';
import { exec } from 'child_process';
import eslint from 'gulp-eslint';
```

**Comment by evitolins** [comment]
My guess is that AirBnB's most recent template added the required the comma-dangle syntax after this tutorial was written.  Maybe the tutorial should be explicit about which AirBnB linting config version is used.

**Comment by ZeVS777** [comment]
`"eslintConfig": {
    "extends": "airbnb",
    "plugins": [
      "import"
    ],
    "rules": {
      "linebreak-style": [
        "error",
        "windows"
      ],
      "comma-dangle": [
        "error",
        "always-multiline"
      ]
    },
    "env": {
      "browser": true
    }
  },`
this config helps me

**Comment by verekia** [comment]
Should not be an issue anymore with the new release of the tutorial.
