### ISSUE TITLE
error Command "start" not found.

### ISSUE THREAD

**Issue by bzbzh** [verekia/js-stack-from-scratch#92]
### Chapter: 7

Following steps up to "Run yarn start, you should now see Webpack building your client-bundle.js" I get this error:
```
yarn start v0.16.1
error Command "start" not found.
```

If I do a gulp, I get:
```
module.js:474
    throw err;
    ^

Error: Cannot find module 'webpack-stream'
```

If I use files from git (chapter 7) I still get this last error.

My node version is v7.1.0.

**Comment by dylnclrk** [comment]
Did you "yarn install"?

**Comment by bzbzh** [comment]
Well I managed to run step 1 to 6 of tutorial before that. 
Is that a specific step of step 7? (if so, what did I overlook from the tutorial?)

**Comment by verekia** [comment]
Did you run `yarn install --dev webpack-stream`? Can you show the `scripts` of your `package.json` file?

**Comment by bzbzh** [comment]
Ok I did it from start anew and it worked. 
Looking at my log file I think I got it wrong because I ran my last yarn installs in my 'src' subfolder (no error came out of this so I had no clue).
_(may be you should add a note about making sure to launch all yarn commands from the root of the project?)_
Thx for the help!

**Comment by jack5505** [comment]
{
  "name": "quickres",
  "version": "0.0.0",
  "description": "Description for quickres",
  "private": true,
  "license": "UNLICENSED",
  "cacheDirectories": [
    "node_modules",
    "src/main/webapp/bower_components"
  ],
  "devDependencies": {
    "bower": "1.7.9",
    "browser-sync": "2.17.0",
    "del": "2.2.2",
    "eslint-config-angular": "0.5.0",
    "eslint-plugin-angular": "2.2.1",
    "event-stream": "3.3.4",
    "generator-jhipster": "4.13.0",
    "gulp": "3.9.1",
    "gulp-angular-filesort": "1.1.1",
    "gulp-angular-templatecache": "2.0.0",
    "gulp-autoprefixer": "3.1.1",
    "gulp-changed": "1.3.2",
    "gulp-cssnano": "2.1.2",
    "gulp-eslint": "3.0.1",
    "gulp-flatten": "0.3.1",
    "gulp-footer": "1.0.5",
    "gulp-htmlmin": "2.0.0",
    "gulp-if": "2.0.1",
    "gulp-imagemin": "3.0.3",
    "gulp-inject": "4.1.0",
    "gulp-natural-sort": "0.1.1",
    "gulp-ng-annotate": "2.0.0",
    "gulp-ng-constant": "1.1.0",
    "gulp-notify": "2.2.0",
    "gulp-plumber": "1.1.0",
    "gulp-rename": "1.2.2",
    "gulp-replace": "0.5.4",
    "gulp-protractor": "4.1.0",
    "gulp-util": "3.0.7",
    "gulp-rev": "7.1.2",
    "gulp-rev-replace": "0.4.3",
    "gulp-sourcemaps": "1.6.0",
    "gulp-uglify": "2.0.0",
    "gulp-useref": "3.1.2",
    "jasmine-core": "2.5.0",
    "jasmine-reporters": "2.2.0",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage": "1.1.1",
    "karma-jasmine": "1.1.0",
    "karma-junit-reporter": "1.2.0",
    "karma-phantomjs-launcher": "1.0.4",
    "karma-script-launcher": "1.0.0",
    "lazypipe": "1.0.1",
    "lodash": "4.15.0",
    "main-bower-files": "2.13.1",
    "map-stream": "0.0.6",
    "phantomjs-prebuilt": "2.1.16",
    "protractor": "5.1.2",
    "protractor-jasmine2-screenshot-reporter": "0.4.1",
    "proxy-middleware": "0.15.0",
    "run-sequence": "1.2.2",
    "workbox-build": "2.1.2",
    "yargs": "5.0.0"
  },
  "engines": {
    "node": ">=6.9.0"
  },
  "scripts": {
    "test": "gulp test",
    "postinstall": "webdriver-manager update"
  }
}
this is my package.json
but yarn start didnt find help please
