### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by taggaddaaaa** [verekia/js-stack-from-scratch#93]
### Type of issue: Translation

Hello! Good tutorial! :100:

I just start translate it to French
Here is the French Version of repo: https://github.com/taggaddaaaa/js-stack-from-scratch  🇫🇷

I'll submit a PR when it's ready

**Comment by verekia** [comment]
Merci :) Just a heads up though, there are some big changes coming up with the v2 of the tutorial. I would say that maybe 60% of the current tutorial remains the same. So it's up to you to wait or not :)

**Comment by taggaddaaaa** [comment]
Mmhhh..; I think I have time to kill at work this few days ;)

**Comment by verekia** [comment]
Alright then! Hmm, between 1 and 3 weeks I think.

**Comment by verekia** [comment]
V2 is out, feel free to start translating it! :)

**Comment by verekia** [comment]
@taggaddaaaa If you are still interested in translating the tutorial V2, let me know in https://github.com/verekia/js-stack-from-scratch/issues/147 :)
